language: r
warnings_are_errors: true
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

r_binary_packages:
  - testthat
  - changepoint
  - dlm
  - fGarch
  - forecast
  - KFAS
  - knitr
  - MASS
  - MSwM
  - strucchange
  - survival
  - timeSeries
  - vars
  - xts

r_github_packages:
  - jimhester/covr

before_install:
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" >> ~/.Rprofile

after_success:
  - Rscript -e 'library(covr);coveralls()'
