language: r
warnings_are_errors: true
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com
   - RGL_USE_NULL: true

apt_packages:
  - freeglut3-dev
  - xvfb
  - xserver-xorg-core
  - xserver-xorg
  - xorg
  - openbox
  - xauth
  - libcurl4-openssl-dev
  - curl

r_binary_packages:
  - testthat
  - cluster
  - changepoint
  - dlm
  - fGarch
  - forecast
  - grDevices
  - KFAS
  - knitr
  - MASS
  - MSwM
  - nlme
  - stats
  - strucchange
  - survival
  - timeSeries
  - tseries
  - utils
  - vars
  - xts
  - zoo
  - lfda

r_github_packages:
  - hadley/devtools
  - jimhester/covr

before_install:
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" >> ~/.Rprofile

after_success:
  - Rscript -e 'library(covr);coveralls()'

after_failure:
  - Rscript -e 'devtools::load_all(); devtools::test()'
